{% set name = "dataframe_image" %}
{% set version = "0.2.6" %}
{% set python_min = "3.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/8c/ab/9a55827fc83e7018ebb79d409f83118ab515d270c5c9dcb12e529f782084/{{ name }}-{{ version }}-py3-none-any.whl
  sha256: c4ab8dced60976efddd13c3be51c2f9929816fc1e547e29443729a2fdce22150

build:
  number: 0
  noarch: python
  entry_points:
    - dataframe_image=dataframe_image._command_line:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - aiohttp >=3.10.2
    - beautifulsoup4
    - cssselect
    - cssutils
    - html2image
    - lxml
    - matplotlib-base >=3.1
    - mistune
    - nbconvert >=5
    - pandas >=0.24
    - pillow
    - python >={{ python_min }}
    - requests

test:
  imports:
    - dataframe_image
    - dataframe_image.convert
    - dataframe_image.export
  commands:
    - pip check
    - dataframe_image --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dexplo/dataframe_image
  summary: Embed pandas DataFrames as images in pdf and markdown files when converting from Jupyter Notebooks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tdpetrou
